version: "3.7"

services:
  redis:
    image: redis:latest
    restart: always
    networks:
      - paperless
    volumes:
      - paperless-redis:/data

  db:
    image: postgres:latest
    restart: always
    networks:
      - paperless
    volumes:
      - paperless-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  paperless:
    image: paperlessngx/paperless-ngx:latest
    restart: always
    depends_on:
      - db
      - redis
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-fs",
          "-S",
          "--max-time",
          "2",
          "http://localhost:8000"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - paperless
      - web
    volumes:
      - paperless-data:/usr/src/paperless/data
      - paperless-media:/usr/src/paperless/media
      - /home/philipp/paperless/export:/usr/src/paperless/export
      - /home/philipp/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 33
      USERMAP_GID: 33
      PAPERLESS_URL: https://dms.philipp.software

    labels:
      - traefik.enable=true
      - traefik.http.routers.paperless.entrypoints=websecure
      - traefik.http.routers.paperless.tls=true
      - traefik.http.routers.paperless.rule=Host(`dms.philipp.software`)
      - traefik.http.routers.paperless.service=paperless
      #- traefik.http.services.paperless.loadbalancer.server.port=8000

networks:
  paperless:
  web:
    external: true

volumes:
  paperless-data:
  paperless-media:
  paperless-db:
  paperless-redis:
