version: "3"

services:
  traefik:
    image: traefik:latest
    restart: always
    container_name: traefik
    networks:
      - web
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config:/etc/traefik/dynamic_conf/
      - ./traefik/letsencrypt:/etc/traefik/letsencrypt/
      - /etc/ssl/philipp.software/:/etc/traefik/certs/
      - ./traefik/user.passwd:/etc/traefik/user.passwd
    labels:
      - traefik.enable=true
      - traefik.http.routers.monitor.entrypoints=websecure
      - traefik.http.routers.monitor.rule=(host(`monitor.philipp.software`) && PathPrefix(`/`))
      - traefik.http.routers.monitor.service=api@internal
      - traefik.http.routers.monitor.tls=true      
      - traefik.http.routers.monitor.middlewares=monitor-auth@file
      - traefik.http.routers.home.entrypoints=websecure
      - traefik.http.routers.home.rule=(host(`philipp.software`) && PathPrefix(`/`))
      - traefik.http.routers.home.tls=true     

  webdav:
    image: bytemark/webdav
    container_name: webdav
    restart: always
    ports:
      - "1111:1111"
    networks:
      - web
    environment:
      AUTH_TYPE: Basic
      LOCATION: /
      SERVER_NAMES: philipp.software,www.philipp.software
    volumes:
      - ./webdav/data:/var/lib/dav
      - ./webdav/user.passwd:/user.passwd
    labels:
      - traefik.enable=true
      - traefik.http.routers.webdav.entrypoints=websecure
      - traefik.http.routers.webdav.rule=(host(`webdav.philipp.software`) && PathPrefix(`/`))
      - traefik.http.routers.webdav.tls=true

networks:
  web:
    external: true
