########################### NETWORKS

networks:
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
  games:
    name: games
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
  default:
    driver: bridge
  # socket_proxy:
  #   name: socket_proxy
  #   driver: bridge
  #   ipam:
  #     config:
  #       - subnet: 192.168.91.0/24
  # dockeripvlan:
  #   external: true
  #   name: br0

########################### SECRETS

secrets:
  postgres_password:
    file: $SECRETSDIR/postgres_password
  # Traefik
  htpasswd:
    file: $SECRETSDIR/htpasswd
  cf_token:
    file: $SECRETSDIR/cf_token
  # Cloudflare
  cf_ddns_token:
    file: $SECRETSDIR/cf_ddns_token
  # Oauth
  traefik_forward_auth:
    file: $SECRETSDIR/traefik_forward_auth
  # Authelia
  authelia_jwt_secret:
    file: $SECRETSDIR/authelia_jwt_secret
  authelia_storage_encryption_key:
    file: $SECRETSDIR/authelia_storage_encryption_key
  authelia_session_secret:
    file: $SECRETSDIR/authelia_session_secret
  authelia_session_redis_password:
    file: $SECRETSDIR/authelia_session_redis_password
  # Borgmatic
  borg_passphrase:
    file: $SECRETSDIR/borg_passphrase
  # Paperless
  paperless_user:
    file: $SECRETSDIR/paperless_user
  paperless_password:
    file: $SECRETSDIR/paperless_password
  paperless_email:
    file: $SECRETSDIR/paperless_email
  paperless_key:
    file: $SECRETSDIR/paperless_key
  # Nextcloud
  nextcloud_admin_user:
    file: $SECRETSDIR/nextcloud_admin_user
  nextcloud_admin_password:
    file: $SECRETSDIR/nextcloud_admin_password
  # Plex
  plex_claim:
    file: $SECRETSDIR/plex_claim

########################### SERVICES
include:
  # CORE
  - compose/traefik.yml
  #- compose/socket-proxy.yml
  - compose/authelia.yml
  # SECURITY
  - compose/crowdsec.yml
  - compose/traefik-bouncer.yml
  - compose/cloudflare-bouncer.yml
  # FRONTEND
  - compose/filebrowser.yml
  - compose/calibre-web.yml
  - compose/portainer.yml
  - compose/nextcloud.yml
  - compose/paperless.yml
  - compose/recipes.yml
  - compose/nginx-recipes.yml
  - compose/overseerr.yml
  - compose/homepage.yml
  - compose/it-tools.yml
  - compose/s-pdf.yml
  - compose/glances.yml
  - compose/website.yml
  - compose/reactive-resume.yml
  - compose/invoiceninja.yml
  - compose/nginx-invoiceninja.yml
  - compose/excalidraw.yml
  # MONITORING
  #- compose/uptime-kuma.yml
  - compose/grafana.yml
  # DATABASE
  - compose/influxdb.yml
  - compose/prometheus.yml
  - compose/postgres-paperless.yml
  - compose/postgres-nextcloud.yml
  - compose/postgres-recipes.yml
  - compose/postgres-reactive-resume.yml
  - compose/redis-paperless.yml
  - compose/redis-nextcloud.yml
  - compose/redis-authelia.yml
  - compose/redis-invoiceninja.yml
  - compose/mysql-invoiceninja.yml
  # UTILITY
  #- compose/adguardhome.yml
  - compose/homeassistant.yml
  - compose/gluetun.yml
  - compose/calibre.yml
  - compose/duplicati.yml
  - compose/borgmatic.yml
  - compose/onlyoffice.yml
  - compose/notifiarr.yml
  - compose/tika.yml
  - compose/gotenberg.yml
  - compose/qdirstat.yml
  - compose/timetagger.yml
  - compose/chrome.yml
  - compose/minio.yml
  # PVR
  - compose/radarr.yml
  - compose/radarr-anime.yml
  - compose/readarr.yml
  - compose/sonarr.yml
  - compose/sonarr-anime.yml
  - compose/prowlarr.yml
  - compose/bazarr.yml
  # DOWNLOADERS
  - compose/qbittorrent.yml
  - compose/sabnzbd.yml
  # MEDIA
  - compose/plex.yml
  - compose/plexmm.yml
  - compose/tautulli.yml
  # MAINTAINANCE
  - compose/cloudflare-ddns.yml
  #- compose/dockergc.yml
  #- compose/watchtower.yml
  #- compose/deunhealth.yml
  # GAMES
  - compose/playit.yml
  - compose/ttt.yml
  - compose/factorio.yml
  - compose/valheim.yml
  - compose/minecraft-allthemods9.yml
  - compose/palworld.yml
  # AI
  - compose/ollama.yml
  - compose/openwebui.yml
  - compose/comfyui.yml
  # DISCORD
  - compose/discord-redbot.yml
  - compose/discord-gsm.yml
  - compose/discord-modmail.yml
  - compose/mongo-modmail.yml
