version: "3.9"

########################### NETWORKS

networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  games:
    name: games
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  dockeripvlan:
    external: true
    name: br0
  # dockervlan:
  #   name: dockervlan
  #   driver: macvlan
  #   driver_opts:
  #     parent: eth0 # using ifconfig
  #   ipam:
  #     config:
  #       - subnet: "192.168.2.0/24"
  #         ip_range: "192.168.2.200/32"
  #         gateway: "192.168.2.1"

########################### SECRETS

secrets:
  postgres_password:
    file: $SECRETSDIR/postgres_password
  # Traefik
  htpasswd:
    file: $SECRETSDIR/htpasswd
  cf_token:
    file: $SECRETSDIR/cf_token
  # Cloudflare
  cf_ddns_token:
    file: $SECRETSDIR/cf_ddns_token
  # Oauth
  traefik_forward_auth:
    file: $SECRETSDIR/traefik_forward_auth
  # Paperless
  paperless_user:
    file: $SECRETSDIR/paperless_user
  paperless_password:
    file: $SECRETSDIR/paperless_password
  paperless_email:
    file: $SECRETSDIR/paperless_email
  paperless_key:
    file: $SECRETSDIR/paperless_key
  # Nextcloud
  nextcloud_admin_user:
    file: $SECRETSDIR/nextcloud_admin_user
  nextcloud_admin_password:
    file: $SECRETSDIR/nextcloud_admin_password
  # Plex
  plex_claim:
    file: $SECRETSDIR/plex_claim
  # Wordpress
  wordpress_db_password:
    file: $SECRETSDIR/wordpress_db_password
  # MySQL
  mysql_root_password:
    file: $SECRETSDIR/mysql_root_password

########################### SERVICES
include:
  # CORE
  - compose/traefik.yml
  - compose/socket-proxy.yml
  - compose/oauth.yml
  # SECURITY
  - compose/crowdsec.yml
  - compose/traefik-bouncer.yml
  - compose/cloudflare-bouncer.yml
  # FRONTEND
  - compose/filebrowser.yml
  - compose/calibre-web.yml
  - compose/portainer.yml
  - compose/nextcloud.yml
  - compose/paperless.yml
  - compose/recipes.yml
  - compose/overseerr.yml
  - compose/homepage.yml
  - compose/speedtest.yml
  - compose/wordpress.yml
  - compose/it-tools.yml
  - compose/s-pdf.yml
  - compose/glances.yml
  - compose/obsidian.yml
  # MONITORING
  - compose/uptime-kuma.yml
  - compose/grafana.yml
  # DATABASE
  - compose/influxdb.yml
  - compose/mysql-wordpress.yml
  - compose/prometheus.yml
  - compose/postgres-paperless.yml
  - compose/postgres-nextcloud.yml
  - compose/postgres-recipes.yml
  - compose/postgres-speedtest.yml
  - compose/redis-paperless.yml
  - compose/redis-nextcloud.yml
  - compose/redis-wordpress.yml
  # UTILITY
  - compose/adguardhome.yml
  - compose/homeassistant.yml
  - compose/gluetun.yml
  - compose/calibre.yml
  - compose/duplicati.yml
  - compose/onlyoffice.yml
  - compose/notifiarr.yml
  - compose/tika.yml
  - compose/gotenberg.yml
  # PVR
  - compose/radarr.yml
  - compose/radarr-anime.yml
  - compose/readarr.yml
  - compose/sonarr.yml
  - compose/sonarr-anime.yml
  - compose/prowlarr.yml
  - compose/bazarr.yml
  # DOWNLOADERS
  - compose/qbittorrent.yml
  - compose/sabnzbd.yml
  # MEDIA
  - compose/plex.yml
  - compose/plexmm.yml
  - compose/tautulli.yml
  # MAINTAINANCE
  - compose/cloudddns-cloud.yml
  - compose/cloudddns-public.yml
  - compose/dockergc.yml
  - compose/watchtower.yml
  - compose/deunhealth.yml
  # GAMES
  - compose/playit.yml
  - compose/ttt.yml
  - compose/factorio.yml
  - compose/minecraft-allthemods9.yml
  - compose/valheim.yml
  - compose/palworld.yml


