global:
  checkNewVersion: true

log:
  level: DEBUG

api:
  insecure: false
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
  imap:
    address: :143/tcp
  smtp:
    address: :25/tcp

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    network: web
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic_conf
    watch: true
