version: '3.7'
services:
   bridge:
      image: shenxn/protonmail-bridge:latest
      container_name: protonmail_bridge
      volumes:
         - protonmail-bridge:/root
      networks:
         - web
      restart: always
      labels:
      - traefik.enable=true
      - traefik.tcp.routers.protonmail_bridge_smtp.entrypoints=smtp
      - traefik.tcp.routers.protonmail_bridge_smtp.tls=true
      - traefik.tcp.routers.protonmail_bridge_smtp.rule=Host(`smtp.philipp.software`)
      - traefik.tcp.routers.protonmail_bridge_imap.entrypoints=imap
      - traefik.tcp.routers.protonmail_bridge_imap.tls=true
      - traefik.tcp.routers.protonmail_bridge_imap.rule=Host(`imap.philipp.software`)

networks:
  web:
    external: true
    
volumes:
   protonmail-bridge: