http:
  middlewares:
    chain-no-auth-compress:
      chain:
        middlewares:
          - middlewares-traefik-bouncer # leave this out if you are not using CrowdSec
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-compress