http:
  middlewares:
    middlewares-nextcloud:
      headers: 
        customFrameOptionsValue: "ALLOW-FROM https://{{env "DOMAINNAME"}}"
        contentSecurityPolicy: "frame-ancestors 'self' {{env "DOMAINNAME"}} *.{{env "DOMAINNAME"}}"
        stsSeconds: 15552011 
        stsIncludeSubdomains: true 
        stsPreload: true
        customResponseHeaders:
          X-Frame-Options: SAMEORIGIN