  collabora:
    <<: *common-keys-apps
    image: collabora/code:latest
    container_name: collabora
    ports:
      - "$COLLABORA_PORT:9980"
    environment:
      domain: $DOMAINNAME|cloud.$DOMAINNAME
      extra_params: --o:ssl.enable=false --o:ssl.termination=true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.collabora-rtr.tls=true"
      - "traefik.http.routers.collabora-rtr.entrypoints=websecure"
      - "traefik.http.routers.collabora-rtr.rule=Host(`collabora.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.collabora-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.collabora-rtr.service=collabora-svc"
      - "traefik.http.services.collabora-svc.loadbalancer.server.port=9980"

  # Traefik Certs Dumper - Extract LetsEncrypt Certificates - Traefik2 Compatible
  certdumper:
    <<: *common-keys-core
    container_name: traefik_certdumper
    image: humenius/traefik-certs-dumper:latest
    command: --restart-containers onlyoffice
    networks:
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $APPDATADIR/traefik/acme:/traefik:ro
      - $SERVICEDIR/shared/certs/:/output:rw
    environment:
      DOMAIN: $DOMAINNAME

  # ProtonmailBridge - ProtonMail IMAP/SMTP Bridge Docker container
  protonmail-bridge:
    <<: *common-keys-core
    container_name: protonmail-bridge
    image: shenxn/protonmail-bridge:2.3.0-1
    ports:
      - 127.0.0.1:$PROTONMAIL_IMAP_PORT:25/tcp #SMTP
      - 127.0.0.1:$PROTONMAIL_SMTP_PORT:143/tcp #IMAP
    volumes:
      - $APPDATADIR/protonmail_bridge:/root

  quakejs:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: 'treyyoder/quakejs:latest'
    container_name: quakejs
    environment:
        - HTTP_PORT=$QUAKEJS_PORT
    ports:
        - "$QUAKEJS_PORT:80"
        - '27960:27960'
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.quake-rtr.entrypoints=http"
      - "traefik.http.routers.quake-rtr.rule=Host(`quake.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.quake-rtr.middlewares=chain-quake-no-redirect@file"
      ## HTTP Services
      - "traefik.http.routers.quake-rtr.service=quake-svc"
      - "traefik.http.services.quake-svc.loadbalancer.server.port=80"