services:
  # Tdarr Server - Library Optimizer
  tdarr:
    image: haveagitgat/tdarr:latest
    container_name: tdarr
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
     - $TDARR_SERVER_PORT:8266
     - $TDARR_WEB_PORT:8265
     - 8267:8267 # node port. It should be mapped on this container because  the node container use the network from the main container
    volumes:
      - $APPDATADIR/tdarr/server:/app/server
      - $APPDATADIR/tdarr/configs:/app/configs
      - $APPDATADIR/tdarr/logs:/app/logs
      - $APPDATADIR/tdarr/Tdarr_Node:/app/Tdarr_Node/assets/app/plugins/
      - $MEDIADIR/transcode/tdarr:/data/temp
      - $MEDIADIR/:/data/media
      - $MEDIADIR/:/data/output
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      serverIP: tdarr # or hostname
      serverPort: 8266
      webUIPort: 8265
      UMASK_SET: 002
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.tdarr-rtr.entrypoints=https"
      - "traefik.http.routers.tdarr-rtr.rule=Host(`tdarr.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.tdarr-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.tdarr-rtr.service=tdarr-svc"
      - "traefik.http.services.tdarr-svc.loadbalancer.server.port=8265"