services:
  # Cloudflare DDNS - Dynamic DNS Updater - public-domain
  cloudddns-public:
    container_name: cloudddns-public
    image: joshava/cloudflare-ddns:latest
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    restart: always
    volumes:
      - $APPDATADIR/cloudflare-ddns-public/config.yaml:/app/config.yaml