services:
  # Cloudflare DDNS - Dynamic DNS Updater
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: favonia/cloudflare-ddns:latest
    networks:
      - t3_proxy
    restart: always
    user: $PUID:$PGID
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=$CLOUDFLARE_DDNS_TOKEN
        # Your Cloudflare API token
      - DOMAINS=$DOMAINNAME,$PUBLIC_DOMAINNAME,www.$DOMAINNAME,www.$PUBLIC_DOMAINNAME
        # Your domains (separated by commas)
      - PROXIED=true
        # Tell Cloudflare to cache webpages and hide your IP (optional)
