services:
  # Homepage - Application Dashboard
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    networks:
      - t3_proxy
      - socket_proxy
    security_opt:
    - no-new-privileges:true
    restart: always
    # ports:
    #  - "$HOMEPAGE_PORT:3000"
    volumes:
      - $APPDATADIR/homepage:/app/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_VAR_PLEX_TOKEN: $PLEX_TOKEN
      HOMEPAGE_VAR_OVERSEERR_TOKEN: $OVERSEERR_API_KEY
      HOMEPAGE_VAR_RADARR_TOKEN: $RADARR_API_KEY
      HOMEPAGE_VAR_SONARR_TOKEN: $SONARR_API_KEY
      HOMEPAGE_VAR_READARR_TOKEN: $READARR_API_KEY
      HOMEPAGE_VAR_QBITTORRENT_PASSWORD: $HOMEPAGE_VAR_QBITTORRENT_PASSWORD
      HOMEPAGE_VAR_ADGUARDHOME_PASSWORD: $HOMEPAGE_VAR_ADGUARDHOME_PASSWORD
      HOMEPAGE_VAR_NEXTCLOUD_TOKEN: $HOMEPAGE_VAR_NEXTCLOUD_TOKEN
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.homepage-rtr.entrypoints=websecure"
      - "traefik.http.routers.homepage-rtr.rule=Host(`homepage.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.homepage-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.homepage-rtr.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadbalancer.server.port=3000"