services:
  # it-tools - Collection of handy online tools for developer
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "$ITTOOLS_PORT:80"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.it-tools-rtr.entrypoints=https"
      - "traefik.http.routers.it-tools-rtr.rule=Host(`it-tools.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.it-tools-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.it-tools-rtr.service=it-tools-svc"
      - "traefik.http.services.it-tools-svc.loadbalancer.server.port=80"