services:
  # Factorio - a game in which you build and maintain factories
  minecraft-allthemods9:
    image: goobaroo/allthemods9:latest
    container_name: minecraft-allthemods9
    networks:
      games:
        ipv4_address: 10.0.2.5
    expose:
      - $MINECRAFT_ALLTHEMODS9_PORT/tcp
    restart: unless-stopped
    volumes:
      - $APPDATADIR/minecraft_allthemods9:/data
    environment:
      EULA: true
      MOTD: "ALL THE MODS 9 on ATHENA"
      JVM_OPTS: "-Xms2G -Xmx24G"