services:
  # minio - High Performance Object Storage (Ractive Resume)
  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "$MINIO_PORT:9000"
    volumes:
      - $APPDATADIR/minio/:/data
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.minio-rtr.entrypoints=https"
      - "traefik.http.routers.minio-rtr.rule=Host(`minio.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.minio-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.minio-rtr.service=minio-svc"
      - "traefik.http.services.minio-svc.loadbalancer.server.port=9000"