services:
  # minio - High Performance Object Storage (Ractive Resume)
  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    command: server /data
    #ports:
    #  - "$MINIO_PORT:9000"
    volumes:
      - $APPDATADIR/minio/:/data
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      MINIO_BROWSER_REDIRECT_URL: https://minio.$PUBLIC_DOMAINNAME
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.minio-rtr.entrypoints=websecure"
      - "traefik.http.routers.minio-rtr.rule=Host(`minio.$PUBLIC_DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.minio-rtr.middlewares=chain-no-auth-public@file"
      ## HTTP Services
      - "traefik.http.routers.minio-rtr.service=minio-svc"
      - "traefik.http.services.minio-svc.loadbalancer.server.port=9000"