services:
  mk-website:
    image: ghcr.io/philipp-mlr/mk-website:main
    container_name: mk-website
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: always
    expose:
      - 1323
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      #CF_TURNSTILE_SECRET: $CF_TURNSTILE_SECRET
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.mk-website-rtr.entrypoints=https"
      - "traefik.http.routers.mk-website-rtr.rule=Host(`mk.$PUBLIC_DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.mk-website-rtr.middlewares.basicauth.users=admin:$$2y$$10$$SE8Omz35IjYykLBtnNFMpu1iofitUil97yrWLl5NP7CBaH/fD1gY"
      ## HTTP Services
      - "traefik.http.routers.mk-website-rtr.service=mk-website-svc"
      - "traefik.http.services.mk-website-svc.loadbalancer.server.port=1323"
