services:
  mongo-modmail:
    image: mongo-modmail
    container_name: mongo-modmail
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_MODMAIL_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_MODMAIL_INITDB_ROOT_PASSWORD
    volumes:
      - $APPDATADIR/mongo_modmail:/data/db