services:
  # Nextcloud - A suite of client-server software for creating and using file hosting services
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    depends_on:
      - redis-nextcloud
      - postgres-nextcloud
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "$NEXTCLOUD_PORT:80"
    volumes:
      - $APPDATADIR/nextcloud/:/var/www/html
      - $APPDATADIR/paperless/consume:/external/consume #has to belong to www-data:www-data
      - /mnt/user/scan:/external/scan #has to belong to www-data:www-data
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_password
    environment:
      # Postgres
      POSTGRES_HOST: postgres-nextcloud
      POSTGRES_DB: $NEXTCLOUD_DATABASE_NAME
      POSTGRES_USER: $NEXTCLOUD_DATABASE_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      # Redis
      REDIS_HOST: redis-nextcloud
      REDIS_HOST_PORT: $REDIS_NEXTCLOUD_PORT
      # Admin
      NEXTCLOUD_ADMIN_USER_FILE: /run/secrets/nextcloud_admin_user
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/nextcloud_admin_password
      # Etc
      TRUSTED_PROXIES: 192.168.90.0/24 $DOMAINNAME
      OVERWRITEPROTOCOL: https
      NEXTCLOUD_TRUSTED_DOMAINS: $DOMAINNAME
      NEXTCLOUD_INIT_HTACCESS: true
      PHP_MEMORY_LIMIT: 4G
      PHP_UPLOAD_LIMIT: 100G
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      #- "traefik.http.routers.nextcloud-rtr-bypass.tls=true"
      #- "traefik.http.routers.nextcloud-rtr-bypass.entrypoints=websecure"
      #- "traefik.http.routers.nextcloud-rtr-bypass.rule=Host(`$DOMAINNAME`) && (PathPrefix(`/remote.php/dav/files`) || PathPrefix(`/apps/onlyoffice`))"
      #- "traefik.http.routers.nextcloud-rtr-bypass.priority=100"
      ## HTTP Routers
      - "traefik.http.routers.nextcloud-rtr.tls=true"
      - "traefik.http.routers.nextcloud-rtr.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-rtr.rule=Host(`cloud.$DOMAINNAME`) || Host(`www.cloud.$DOMAINNAME`)"
      #- "traefik.http.routers.nextcloud-rtr.priority=99"
      ## Middlewares
      #- "traefik.http.routers.nextcloud-rtr-bypass.middlewares=chain-nextcloud-no-auth@file"
      #- "traefik.http.routers.nextcloud-rtr.middlewares=chain-nextcloud-oauth@file"  # Uncomment this
      - "traefik.http.routers.nextcloud-rtr.middlewares=chain-nextcloud-no-auth@file" # Comment out this
      ## HTTP Services
      #- "traefik.http.routers.nextcloud-rtr-bypass.service=nextcloud-svc"
      - "traefik.http.routers.nextcloud-rtr.service=nextcloud-svc"
      - "traefik.http.services.nextcloud-svc.loadbalancer.server.port=80"