services:
  #Notifiarr - Enables content requests from Media Bot
  notifiarr:
    image: golift/notifiarr:latest
    container_name: notifiarr
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "$NOTIFIARR_PORT:5454"
    volumes:
      - $APPDATADIR/notifiarr:/config
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DN_API_KEY: $NOTIFIARR_API_KEY
      DN_UI_PASSWORD: $NOTIFIARR_UI_PASSWORD
      # Prowlarr
      DN_PROWLARR_0_NAME: Prowlarr
      DN_PROWLARR_0_URL: http://prowlarr:$PROWLARR_PORT
      DN_PROWLARR_0_API_KEY: $PROWLARR_API_KEY
      # Radarr
      DN_RADARR_0_NAME: Radarr
      DN_RADARR_0_URL: http://radarr:$RADARR_PORT
      DN_RADARR_0_API_KEY: $RADARR_API_KEY
      # Sonarr
      DN_SONARR_0_NAME: Sonarr
      DN_SONARR_0_URL: http://sonarr:$SONARR_PORT
      DN_SONARR_0_API_KEY: $SONARR_API_KEY
      # Readarr
      DN_READARR_0_NAME: Readarr
      DN_READARR_0_URL: http://readarr:$READARR_PORT
      DN_READARR_0_API_KEY: $READARR_API_KEY
      # Plex
      DN_PLEX_URL: http://plex:$PLEX_PORT
      DN_PLEX_TOKEN: 
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.notifiarr-rtr.entrypoints=https"
      - "traefik.http.routers.notifiarr-rtr.rule=Host(`notifiarr.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.notifiarr-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.notifiarr-rtr.service=notifiarr-svc"
      - "traefik.http.services.notifiarr-svc.loadbalancer.server.port=5454"