services:
  # playit.gg - a global proxy that allows anyone to host a server without port forwarding
  playit:
    image: embeddedt/playit
    container_name: playit
    networks:
      games:
        ipv4_address: 10.1.0.2
    restart: unless-stopped
    volumes:
      - $APPDATADIR/playit/:/etc/playit