services:
  # Portainer - WebUI for Containers
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    networks:
      - t3_proxy
    security_opt:
    - no-new-privileges:true
    restart: always
    ports:
      - "$PORTAINER_PORT:9000"
    volumes:
      - $APPDATADIR/portainer/data:/data # Change to local directory if you want to save/transfer config locally
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.portainer-rtr.entrypoints=websecure"
      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.portainer-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"