services:
  # Postgres - Open source object-relational database (Recipes)
  postgres-recipes:
    image: postgres:15
    container_name: postgres-recipes
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    restart: always
    ports:
      - "$POSTGRES_RECIPES_PORT:5432"
    volumes:
      - $APPDATADIR/postgres_recipes/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $RECIPES_DATABASE_NAME
      POSTGRES_USER: $RECIPES_DATABASE_USER
      POSTGRES_PASSWORD: $RECIPES_DATABASE_PASSWORD