services:
  # Postgres - Open source object-relational database (Immich)
  postgres-immich:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    container_name: postgres-immich
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: always
    expose:
      - 5432
    volumes:
      - $APPDATADIR/postgres_immich/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $IMMICH_DATABASE_NAME
      POSTGRES_USER: $IMMICH_DATABASE_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    secrets:
      - postgres_password