services:
  # Postgres - Open source object-relational database (Nextcloud)
  postgres-nextcloud:
    image: postgres:15
    container_name: postgres-nextcloud
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    restart: always
    ports:
      - "$POSTGRES_NEXTCLOUD_PORT:5432"
    volumes:
      - $APPDATADIR/postgres_nextcloud/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $NEXTCLOUD_DATABASE_NAME
      POSTGRES_USER: $NEXTCLOUD_DATABASE_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password