services:
  #ProtonMail Bridge - Use your ProtonMail account with any email client
  protonbridge:
    image: ganeshlab/protonmail-bridge:latest
    container_name: protonmail-bridge
    ports:
      - '1025:1025/tcp'
      - '1143:1143/tcp'
    volumes:
      - "$APPDATADIR/protonmail-bridge:/root"
    restart: unless-stopped