services:
  # redis - In memory key-value store - (Paperless-ngx: Task scheduler and advanced features)
  redis-paperless:
    image: redis:latest
    container_name: redis-paperless
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    restart: always
    command: --port $REDIS_PAPERLESS_PORT
    ports:
      - "$REDIS_PAPERLESS_PORT:$REDIS_PAPERLESS_PORT"
    volumes:
      - $APPDATADIR/redis_paperless/:/data