services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    devices:
        - /dev/sda
        - /dev/sdb
        - /dev/sdc
        - /dev/sdd    
        - /dev/sde
        - /dev/sdf
        - /dev/nvme0
        - /dev/nvme1
    priviliged: true
    networks:
      - podman
    cap_add:
        - SYS_RAWIO
        - SYS_ADMIN #NVMe support
    restart: always
    ports:
      - $SCRUTINY_PORT:8080
    volumes:
      - $APPDATADIR/scrutiny:/opt/scrutiny/config
      - /run/udev:/run/udev:ro

networks:
  podman:
    external: true