services:
  timetagger:
    image: ghcr.io/almarklein/timetagger:latest
    container_name: timetagger
    restart: unless-stopped
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    expose:
      - "8080"
    volumes:
      - $APPDATADIR/timetagger:/opt/_timetagger
    environment:
      TIMETAGGER_BIND: 0.0.0.0:80    
      TIMETAGGER_DATADIR: /opt/_timetagger
      TIMETAGGER_LOG_LEVEL: info
      TIMETAGGER_CREDENTIALS: $TIMETAGGER_CREDENTIALS
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.timetagger-rtr.entrypoints=websecure"
      - "traefik.http.routers.timetagger-rtr.rule=Host(`tracking.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.timetagger-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.timetagger-rtr.service=timetagger-svc"
      - "traefik.http.services.timetagger-svc.loadbalancer.server.port=80"