services:
  # VSCode - VSCode Editing
  vscode:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vscode
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "$VSCODE_PORT:8443"
    volumes:
      - $APPDATADIR/vscode:/config
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      FILE__PASSWORD_HASH: /run/secrets/vscode_password_hash
      FILE__SUDO_PASSWORD_HASH: /run/secrets/vscode_sudo_password_hash
      DEFAULT_WORKSPACE: /config/workspace
      PROXY_DOMAIN: code.$DOMAINNAME
    secrets:
      - vscode_password_hash
      - vscode_sudo_password_hash
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.vscode-rtr.entrypoints=https"
      - "traefik.http.routers.vscode-rtr.rule=Host(`code.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.vscode-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.vscode-rtr.service=vscode-svc"
      - "traefik.http.services.vscode-svc.loadbalancer.server.port=8443"