services:
  # WatchTower - Automatic Docker Container Updates
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    depends_on:
      - socket-proxy
    networks:
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    restart: always
    volumes:
      - $APPDATADIR/watchtower/config.json:/config.json
    environment:
      TZ: $TZ
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_REVIVE_STOPPED: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "false"
      WATCHTOWER_SCHEDULE: "*/3 * * * *" # Everyday at 12:30
      DOCKER_HOST: tcp://socket-proxy:2375 # Use this if you have Socket Proxy enabled.