version: "3.7"
services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - portainer-data:/data
    restart: always
    networks:
      - internal
    security_opt:
      - 'no-new-privileges:true'
    labels:
    - traefik.enable=true
    # Frontend
    - traefik.http.routers.portainer-frontend.entrypoints=websecure
    - traefik.http.routers.portainer-frontend.rule=Host(`portainer.philipp.software`)
    - traefik.http.services.portainer-frontend.loadbalancer.server.port=9000
    - traefik.http.routers.portainer-frontend.service=portainer-frontend
    - traefik.http.routers.portainer-frontend.tls=true

    # Edge
    - traefik.http.routers.portainer-edge.rule=Host(`edge.philipp.software`)
    - traefik.http.routers.portainer-edge.entrypoints=websecure
    - traefik.http.services.portainer-edge.loadbalancer.server.port=8000
    - traefik.http.routers.portainer-edge.service=portainer-edge
    - traefik.http.routers.portainer-edge.tls=true

networks:
  internal:
  
volumes:
  portainer-data: